configServiceAddress:
  ip: 127.0.0.1
  port: 9001
grpcOuterAddress:
  #ip: 127.0.0.1
  port: 9004
grpcInnerAddress:
  ip: 0.0.0.0
  port: 9004
moduleName: router

HttpServerHost: localhost
HttpServerPort: 9513

logfile:
  path: /var/log/isp-routing-service/runtime.log
  maxSizeMb: 512
  maxBackups: 4
  compress: true

infraServerPort: 9554
